name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - "releases/**"

jobs:
  python-format:
    name: Python format
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          cache: true
      - run: pixi run format --check --diff

  pytest:
    name: Python tests (${{ matrix.environment }})
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - test-py38pa6
          - test-py38
          - test-py39
          - test-py311
          - test-py311kn55
          - test-py312kn56
          - test-py313kn56
          - test-py314kn56
    steps:
      - uses: actions/checkout@v5
      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          cache: true
      - run: pixi run -e ${{ matrix.environment }} test

  js-lint-test-build:
    name: JS lint, tests, and build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: org.knime.python3.scripting.nodes/js-src
    steps:
      - uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: org.knime.python3.scripting.nodes/js-src/package.json
          cache: npm
          cache-dependency-path: org.knime.python3.scripting.nodes/js-src/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run type-check
      - name: Lint and format check
        run: npm run ci:lint-format
      - name: Run coverage
        run: npm run coverage
      - name: Audit
        run: npm run audit
      - name: Build
        run: npm run build
